### PR TITLE
fix: compilation error

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Fixing a complication error caused by PR https://github.com/medibloc/panacea-oracle/pull/38. Sorry for not updating the branch before merging that PR.

### CODE REVIEW

**Review by gyuguen — APPROVED** [review]
LGTM
